gpu_devices: null
backbone_layers:
- 2
- 3
- 7
betas:
- 0.9
- 0.999
batchsize: 64
bos_token: 1
channels: 1
data: dataset/data/train_new_192.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
dim: 256
encoder_depth: 4
eos_token: 2
epochs: 500
gamma: 0.9995
heads: 8
id: null
load_chkpt: Null
lr: 0.001
lr_step: 30
max_height: 192
max_seq_len: 512
max_width: 672
micro_batchsize: -1
min_height: 16
min_width: 16
model_path: checkpoints
name: pix2tex
num_layers: 4
num_tokens: 8000
optimizer: Adam
output_path: outputs
pad: false
pad_token: 0
patch_size: 16
sample_freq: 6000
save_freq: 5
scheduler: StepLR
seed: 42
encoder_structure: hybrid
temperature: 0.2
test_samples: 5
testbatchsize: 50
tokenizer: dataset/tokenizer.json
valbatches: 1000
valdata: dataset/data/val_new_192.pkl
